development:
  adapter: postgresql
  encoding: unicode
  database: jobs_development
  pool: 5
  username: seanperryman
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: jobs_test
  pool: 5
  username: seanperryman
  password: